### ISSUE TITLE
All issues and notices that I am aware of

### ISSUE THREAD

**Issue by situ0020** [situ0020/situ0020.github.io#1]
NOTICE: I WILL INCLUDE A TYPE AND GRID SYSTEM FOR THE ACTUAL DEADLINE.

NOTICE: I HAVE UNKNOWN ERRORS DUE TO THE FLEXSLIDER AND VIEWPORTS IN THE CSS. LET ME KNOW IF THERE IS ANY WAY TO FIX IT.

HELP WANTED FOR NAVIGATION SECTION: I'd prefer if the navigation closed when selecting a page, but it just stays open. Cannot figure out how to uncover navigation menu when scrolling to this slideshow section.

HELP WANTED FOR THE PORTFOLIO SECTION: Slideshow is unable to move on mobile. I'm not sure why and have looked it over. Also, I can't seem to find how to fix the appearance of the prev/next arrows.

**Comment by card0127** [comment]
Add info to the services section. scrolling effect, parallax effect to the top section.

**Comment by card0127** [comment]
Suggestion for the nav staying open... have a look at the final assignment we did for Tiffany. It will give you some hints on how to fix it.

**Comment by cole0228** [comment]
I feel like the icons for graphic & web design, photography, etc need to have a  link going somewhere maybe to a project that is what the icons subject is.

**Comment by cole0228** [comment]
your website keeps crashing/freezing the safari on my phone whenever it gets to your portfolio pieces so I think maybe something is up with that.
