### ISSUE TITLE
HELP WANTED FOR THE PORTFOLIO SECTION: 

### ISSUE THREAD

**Issue by situ0020** [situ0020/situ0020.github.io#5]
Slideshow is unable to move on mobile. I'm not sure why and have looked it over. Also, I can't seem to find how to fix the appearance of the prev/next arrows.

**Comment by thomasjbradley** [comment]
On specific phones?

**Comment by situ0020** [comment]
I've realized it works by sliding your finger on the screen. Though, the website tends to crash on mobile and I believe it's due to the flexslider.

**Comment by situ0020** [comment]
I've figured it out, but I'm not too sure this is an ideal solution for it. I've changed 'useCSS: true' to  'useCSS: false' in 'jquery.flexslider.js' and everything works well on mobile.

**Comment by thomasjbradley** [comment]
Yeah, not ideal, but if it works, it's good.
